-- ============================================================
-- MONATIZA - PUBLICIDADE COMERCIAL PRÓPRIA
-- Migration 0031
--
-- Cria:
-- 1. Tabela commercial_ads
-- 2. Dois espaços comerciais fixos da Home
-- 3. Bucket público para artes publicitárias
-- 4. Leitura pública dos anúncios ativos
-- 5. Escrita restrita a administradores
-- ============================================================


-- ============================================================
-- 1. TABELA
-- ============================================================

create table if not exists public.commercial_ads (
  id bigint generated by default as identity primary key,

  position integer not null unique
    check (position in (1, 2)),

  name text not null,

  desktop_image_url text,
  mobile_image_url text,

  target_url text,

  active boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================
-- 2. CRIA OS DOIS ESPAÇOS FIXOS
-- ============================================================

insert into public.commercial_ads (
  position,
  name,
  active
)
values
  (1, 'Espaço Comercial 1', false),
  (2, 'Espaço Comercial 2', false)
on conflict (position) do nothing;


-- ============================================================
-- 3. ATUALIZA updated_at AUTOMATICAMENTE
-- ============================================================

create or replace function public.update_commercial_ads_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists commercial_ads_updated_at
on public.commercial_ads;

create trigger commercial_ads_updated_at
before update on public.commercial_ads
for each row
execute function public.update_commercial_ads_updated_at();


-- ============================================================
-- 4. RLS
-- ============================================================

alter table public.commercial_ads enable row level security;


-- Visitantes podem ler SOMENTE anúncios ativos.
drop policy if exists "Public can read active commercial ads"
on public.commercial_ads;

create policy "Public can read active commercial ads"
on public.commercial_ads
for select
to anon, authenticated
using (active = true);


-- ============================================================
-- 5. ADMIN PODE VISUALIZAR TODOS
-- ============================================================

drop policy if exists "Admins can read all commercial ads"
on public.commercial_ads;

create policy "Admins can read all commercial ads"
on public.commercial_ads
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'admin'
  )
);


-- ============================================================
-- 6. ADMIN PODE ATUALIZAR OS DOIS ESPAÇOS
-- ============================================================

drop policy if exists "Admins can update commercial ads"
on public.commercial_ads;

create policy "Admins can update commercial ads"
on public.commercial_ads
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'admin'
  )
);


-- ============================================================
-- 7. STORAGE PARA AS ARTES
-- ============================================================

insert into storage.buckets (
  id,
  name,
  public
)
values (
  'commercial-ads',
  'commercial-ads',
  true
)
on conflict (id) do update
set public = true;


-- ============================================================
-- 8. LEITURA PÚBLICA DAS IMAGENS
-- ============================================================

drop policy if exists "Public can view commercial ad images"
on storage.objects;

create policy "Public can view commercial ad images"
on storage.objects
for select
to public
using (
  bucket_id = 'commercial-ads'
);


-- ============================================================
-- 9. ADMIN PODE ENVIAR IMAGENS
-- ============================================================

drop policy if exists "Admins can upload commercial ad images"
on storage.objects;

create policy "Admins can upload commercial ad images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'commercial-ads'
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'admin'
  )
);


-- ============================================================
-- 10. ADMIN PODE SUBSTITUIR IMAGENS
-- ============================================================

drop policy if exists "Admins can update commercial ad images"
on storage.objects;

create policy "Admins can update commercial ad images"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'commercial-ads'
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'admin'
  )
)
with check (
  bucket_id = 'commercial-ads'
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'admin'
  )
);


-- ============================================================
-- 11. ADMIN PODE EXCLUIR IMAGENS
-- ============================================================

drop policy if exists "Admins can delete commercial ad images"
on storage.objects;

create policy "Admins can delete commercial ad images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'commercial-ads'
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'admin'
  )
);